### ISSUE TITLE
Possibility to fake renounce ownership

### ISSUE THREAD

**Issue by ballinger-guillaume** [HUP-LIFE/HUP#2]
Hello,
as you can see above there is something rather concerning in the code.

```sol

 function lock(uint256 time) public virtual onlyOwner {
      
      
                _previousOwner = _owner;
      
      
                _owner = address(0);
      
      
                _lockTime = block.timestamp + time;
      
      
                emit OwnershipTransferred(_owner, address(0));
      
      
            }
      
      
            
      
      
            function unlock() public virtual {
      
      
                require(_previousOwner == msg.sender, "You don't have permission to unlock");
      
      
                require(block.timestamp &gt; _lockTime , "Contract is still locked");
      
      
                emit OwnershipTransferred(_owner, _previousOwner);
      
      
                _owner = _previousOwner;
      
      
            }
```
So with this calling lock(0) => unlock => renounce ownership => unlock can make it look like the ownership was renounced even though there is a backdoor to get it back.

By calling lock the previous owner is set to the owner.
By calling unlock the owner is set to the previous owner but the previous owner isn't erased.
By calling renounce ownership owner is set to 0x0
By calling unlock this is totally possible.
previousOwner is still the "ex"owner so the first requirement is passing. The time is also required and then the previous owner is set to the owner.

This could be misused and any trace of lock and unlock + previous owner should be removed from the token. Otherwise, the owner could easily rug by setting the transaction fees to 100% and exclude his own address (cf Fairmoon)

**Comment by agungn10116412** [comment]
hope there is an update about this

**Comment by HUPLIFE** [comment]
@agungn10116412, we know trust is paramount to the community, and we thank you for your report. This particular matter was addressed by HAECHI in their audit, and we will be implementing the recommendations of both them and CertiK (which will be conducting their own independent report). Here is are where the audit reports will be published when we get them: https://github.com/HUP-LIFE/Audits/

**Comment by tmoux** [comment]
Hi, I looked at the post-audit Ownable contract (https://github.com/HUP-LIFE/HUP/pull/6/files) and I still don't think the original issue @ballinger-guillaume brought up has been addressed. The unlock function
```    
function unlock() public virtual {
        require(_previousOwner == msg.sender, "You don't have permission to unlock");
        require(block.timestamp > _lockTime , "Contract is still locked");
        emit OwnershipTransferred(_owner, _previousOwner);
        _owner = _previousOwner;
}
```
still does not reset the value of `_previousOwner` after it is called. This means that if the owner calls `unlock()`, he can then renounce or transfer ownership, at which point he should not be able to be the owner. However, he can then forcibly take back ownership by calling `unlock()`, since he is still the `_previousOwner`. I do not believe this issue has been addressed in the HAECHI audit.

A simple fix would be to add the line `_previousOwner = address(0);` to the end of the `unlock` function, preventing it from being called when the contract is already unlocked.
